package ru.inex.autotestconfig.modeldata.trainmodels;

import java.util.ArrayList;
import java.util.List;

public class TestData {
	public static List<Country> getCountries() {
		List<Country> countries = new ArrayList<Country>();
		
		countries.add(new Country("Абхазия"));
		countries.add(new Country("Австралия"));
		countries.add(new Country("Австрия"));
		countries.add(new Country("Азерайджан"));
		countries.add(new Country("Албания"));
		countries.add(new Country("Алжир"));
		countries.add(new Country("Американский Самоа"));
		countries.add(new Country("Ангилья"));
		countries.add(new Country("Ангола"));
		countries.add(new Country("Андорра"));
		countries.add(new Country("Антарктика"));
		countries.add(new Country("Антигуа и Барбуда"));
		countries.add(new Country("Антильские острова"));
		countries.add(new Country("Арабские Эмираты"));
		countries.add(new Country("Аргентина"));
		countries.add(new Country("Армения"));
		countries.add(new Country("Аруба"));
		countries.add(new Country("Афганистан"));
		countries.add(new Country("Багамские острова"));
		countries.add(new Country("Бангладеш"));
		countries.add(new Country("Барбадос"));
		countries.add(new Country("Бахрейн"));
		countries.add(new Country("Беларусь"));
		countries.add(new Country("Белиз"));
		countries.add(new Country("Бельгия"));
		countries.add(new Country("Бенин"));
		countries.add(new Country("Бермуды"));
		countries.add(new Country("Болгария"));
		countries.add(new Country("Боливия"));
		countries.add(new Country("Босния и Герцеговина"));
		countries.add(new Country("Ботсвана"));
		countries.add(new Country("Бразилия"));
		countries.add(new Country("Британские территории Индийского океана"));
		countries.add(new Country("Бруней"));
		countries.add(new Country("Буркина Фасо"));
		countries.add(new Country("Бурунди"));
		countries.add(new Country("Бутан"));
		countries.add(new Country("Вануату"));
		countries.add(new Country("Ватикан"));
		countries.add(new Country("Великобритания"));
		countries.add(new Country("Венгрия"));
		countries.add(new Country("Венесуэла"));
		countries.add(new Country("Виргинские острова (Британские)"));
		countries.add(new Country("Виргинские острова (США)"));
		countries.add(new Country("Восточный Тимор"));
		countries.add(new Country("Вьетнам"));
		countries.add(new Country("Габон"));
		countries.add(new Country("Гаити"));
		countries.add(new Country("Гайана"));
		countries.add(new Country("Гамбия"));
		countries.add(new Country("Гана"));
		countries.add(new Country("Гваделупа"));
		countries.add(new Country("Гватемала"));
		countries.add(new Country("Гвинея"));
		countries.add(new Country("Гвинея-Бисау"));
		countries.add(new Country("Германия"));
		countries.add(new Country("Гибралтар"));
		countries.add(new Country("Гондурас"));
		countries.add(new Country("Гонконг (Китай)"));
		countries.add(new Country("Гренада"));
		countries.add(new Country("Гренландия"));
		countries.add(new Country("Греция"));
		countries.add(new Country("Грузия"));
		countries.add(new Country("Гуам"));
		countries.add(new Country("Дания"));
		countries.add(new Country("Демократическая республика Конго"));
		countries.add(new Country("Джибути"));
		countries.add(new Country("Доминика"));
		countries.add(new Country("Доминиканская республика"));
		countries.add(new Country("Египет"));
		countries.add(new Country("ЕС"));
		countries.add(new Country("Замбия"));
		countries.add(new Country("Западная Сахара"));
		countries.add(new Country("Зимбабве"));
		countries.add(new Country("Израиль"));
		countries.add(new Country("Индия"));
		countries.add(new Country("Индонезия"));
		countries.add(new Country("Иордания"));
		countries.add(new Country("Ирак"));
		countries.add(new Country("Иран"));
		countries.add(new Country("Ирландия"));
		countries.add(new Country("Исландия"));
		countries.add(new Country("Испания"));
		countries.add(new Country("Италия"));
		countries.add(new Country("Йемен"));
		countries.add(new Country("Казахстан"));
		countries.add(new Country("Каймановы острова"));
		countries.add(new Country("Камбоджа"));
		countries.add(new Country("Камерун"));
		countries.add(new Country("Канада"));
		countries.add(new Country("Катар"));
		countries.add(new Country("Кения"));
		countries.add(new Country("Кипр"));
		countries.add(new Country("Кирибати"));
		countries.add(new Country("Китайская Народная Республика"));
		countries.add(new Country("Кокосовые острова"));
		countries.add(new Country("Колумбия"));
		countries.add(new Country("Коморские острова"));
		countries.add(new Country("Конго"));
		countries.add(new Country("Корейская Народная Демократическая республика"));
		countries.add(new Country("Корея"));
		countries.add(new Country("Коста Рика"));
		countries.add(new Country("Кот-д'Ивуар"));
		countries.add(new Country("Куба"));
		countries.add(new Country("Кувейт"));
		countries.add(new Country("Кыргызстан"));
		countries.add(new Country("Лаос"));
		countries.add(new Country("Латвия"));
		countries.add(new Country("Лесото"));
		countries.add(new Country("Либерия"));
		countries.add(new Country("Ливан"));
		countries.add(new Country("Ливия"));
		countries.add(new Country("Литва"));
		countries.add(new Country("Лихтенштейн"));
		countries.add(new Country("Люксембург"));
		countries.add(new Country("Маврикий"));
		countries.add(new Country("Мавритания"));
		countries.add(new Country("Мадагаскар"));
		countries.add(new Country("Майотта"));
		countries.add(new Country("Макао (Китай)"));
		countries.add(new Country("Македония"));
		countries.add(new Country("Малави"));
		countries.add(new Country("Малайзия"));
		countries.add(new Country("Мали"));
		countries.add(new Country("Мальдивские острова"));
		countries.add(new Country("Мальта"));
		countries.add(new Country("Марианские острова"));
		countries.add(new Country("Марокко"));
		countries.add(new Country("Мартиника"));
		countries.add(new Country("Маршалловы острова"));
		countries.add(new Country("Мексика"));
		countries.add(new Country("Микронезия"));
		countries.add(new Country("Мозамбик"));
		countries.add(new Country("Молдова"));
		countries.add(new Country("Монако"));
		countries.add(new Country("Монголия"));
		countries.add(new Country("Монтсеррат"));
		countries.add(new Country("Мьянма"));
		countries.add(new Country("Намибия"));
		countries.add(new Country("Науру"));
		countries.add(new Country("Непал"));
		countries.add(new Country("Нигер"));
		countries.add(new Country("Нигерия"));
		countries.add(new Country("Нидерланды"));
		countries.add(new Country("Никарагуа"));
		countries.add(new Country("Ниуэ"));
		countries.add(new Country("Новая Зеландия"));
		countries.add(new Country("Новая Каледония"));
		countries.add(new Country("Норвегия"));
		countries.add(new Country("Оман"));
		countries.add(new Country("ООН"));
		countries.add(new Country("остров Буве"));
		countries.add(new Country("остров Норфолк"));
		countries.add(new Country("остров Питкэрн"));
		countries.add(new Country("остров Рождества"));
		countries.add(new Country("остров Святой Елены"));
		countries.add(new Country("острова Валлис и Футуна"));
		countries.add(new Country("острова Герда и МакДональда"));
		countries.add(new Country("острова Зеленого Мыса"));
		countries.add(new Country("острова Кука"));
		countries.add(new Country("острова Самоа"));
		countries.add(new Country("острова Свалбард и Ян Майен"));
		countries.add(new Country("острова Туркс и Кайкос"));
		countries.add(new Country("Отдаленные Острова США"));
		countries.add(new Country("Пакистан"));
		countries.add(new Country("Палау"));
		countries.add(new Country("Палестина"));
		countries.add(new Country("Панама"));
		countries.add(new Country("Папуа - Новая Гвинея"));
		countries.add(new Country("Парагвай"));
		countries.add(new Country("Перу"));
		countries.add(new Country("Польша"));
		countries.add(new Country("Португалия"));
		countries.add(new Country("Пуэрто-Рико"));
		countries.add(new Country("Реюньон"));
		countries.add(new Country("Россия"));
		countries.add(new Country("Руанда"));
		countries.add(new Country("Румыния"));
		countries.add(new Country("Сальвадор"));
		countries.add(new Country("Сан-Марино"));
		countries.add(new Country("Сан-Томе и Принсипи"));
		countries.add(new Country("Саудовская Аравия"));
		countries.add(new Country("Свазиленд"));
		countries.add(new Country("Северная Ирландия"));
		countries.add(new Country("Сейшельские острова"));
		countries.add(new Country("Сен-Пьер и Микелон"));
		countries.add(new Country("Сенегал"));
		countries.add(new Country("Сент-Винсент и Гренадины"));
		countries.add(new Country("Сент-Китс и Невис"));
		countries.add(new Country("Сент-Люсия"));
		countries.add(new Country("Сербия"));
		countries.add(new Country("Сингапур"));
		countries.add(new Country("Сирия"));
		countries.add(new Country("Словакия"));
		countries.add(new Country("Словения"));
		countries.add(new Country("Соединенные Штаты Америки"));
		countries.add(new Country("Соломоновы острова"));
		countries.add(new Country("Сомали"));
		countries.add(new Country("Судан"));
		countries.add(new Country("Суринам"));
		countries.add(new Country("Сьерра-Леоне"));
		countries.add(new Country("Таджикистан"));
		countries.add(new Country("Тайвань (Республика Китай)"));
		countries.add(new Country("Тайланд"));
		countries.add(new Country("Танзания"));
		countries.add(new Country("Того"));
		countries.add(new Country("Токелау"));
		countries.add(new Country("Тонга"));
		countries.add(new Country("Тринидад и Тобаго"));
		countries.add(new Country("Тувалу"));
		countries.add(new Country("Тунис"));
		countries.add(new Country("Туркменистан"));
		countries.add(new Country("Турция"));
		countries.add(new Country("Уганда"));
		countries.add(new Country("Узбекистан"));
		countries.add(new Country("Украина"));
		countries.add(new Country("Уругвай"));
		countries.add(new Country("Уэльс"));
		countries.add(new Country("Фарерские острова"));
		countries.add(new Country("Фиджи"));
		countries.add(new Country("Филиппины"));
		countries.add(new Country("Финляндия"));
		countries.add(new Country("Фолклендские (Мальвинские) острова"));
		countries.add(new Country("Франция"));
		countries.add(new Country("Французская Гвиана"));
		countries.add(new Country("Французская Полинезия"));
		countries.add(new Country("Французские Южные Территории"));
		countries.add(new Country("Хорватия"));
		countries.add(new Country("Центральная Африканская Республика"));
		countries.add(new Country("Чад"));
		countries.add(new Country("Черногория"));
		countries.add(new Country("Чехия"));
		countries.add(new Country("Чили"));
		countries.add(new Country("Швейцария"));
		countries.add(new Country("Швеция"));
		countries.add(new Country("Шотландия"));
		countries.add(new Country("Шри Ланка"));
		countries.add(new Country("Эквадор"));
		countries.add(new Country("Экваториальная Гвинея"));
		countries.add(new Country("Эритрея"));
		countries.add(new Country("Эстония"));
		countries.add(new Country("Эфиопия"));
		countries.add(new Country("ЮАР"));
		countries.add(new Country("Югославия"));
		countries.add(new Country("Южная Георгия и Южные Сандвичевы острова"));
		countries.add(new Country("Ямайка"));
		countries.add(new Country("Япония"));

		return countries;
	}
}
